#!/bin/bash

lnx=3.13.5

if [ "$USER" = "fberarde" ]
then
    lnx=3.13.3
fi
    

./app_render_gtk.py ~/espaces/travail/linux-$lnx/ x86 x86_64_defconfig
find . -name "*.pyc" -exec rm -vf {} \; -o -name "*~" -exec rm -vf {} \;
