#!/bin/sh

path=~/espaces/travail
lnx=3.13.5

if [ "$USER" = "fberarde" ]
then
    lnx=3.13.3
elif [ "$USER" = "mlemasso" ]
then
    lnx=3.13.5
elif [ "$USER" = "oxyasis" ]
then
    path=/home/oxyasis/git
    lnx=3.13.6
elif [ "$USER" = "bthiaola" ]
then
    lnx=3.13
elif [ "$USER" = "jaupetit" ]
then
    path=/net/travail/jaupetit
    lnx=3.13.5
fi


./main.py $path/linux-$lnx/ x86 x86_64
find . -name "*.pyc" -exec rm -f {} \; -o -name "*~" -exec rm -f {} \;
